---
abstract: 'turns articles into dynamic templates.'
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: 'GPL version 2'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RTFM-Extension-ArticleTemplates
no_index:
  directory:
    - html
    - inc
    - t
requires:
  RT::FM: 2.2.2
  perl: 5.8.3
version: 0.01
