---
abstract: 'turns articles into dynamic templates'
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ArticleTemplates
no_index:
  directory:
    - html
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.04
