---
abstract: 'turns articles into dynamic templates.'
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: 'GPL version 2'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTFM-Extension-ArticleTemplates
no_index:
  directory:
    - etc
    - html
    - po
    - var
    - inc
    - t
requires:
  perl: 5.8.3
version: 0.02
